CREATE TABLE IF NOT EXISTS PRODUCT
(
  IDT_PRODUCT  NUMBER(10,0)  NOT NULL,
  COD_PRODUCT  VARCHAR2(60)  NOT NULL,
  DES_PRODUCT  VARCHAR2(60)  NOT NULL,
);

CREATE SEQUENCE IF NOT EXISTS SQ_PRODUCT_IDT START WITH 1;