DELETE FROM PRODUCT;
DELETE FROM SALES;
DELETE FROM SALES_PRODUCT;


DROP SEQUENCE SQ_PRODUCT_IDT;
DROP SEQUENCE SQ_SALES_IDT;
DROP SEQUENCE SQ_SALES_PRODUCT_IDT;

CREATE SEQUENCE IF NOT EXISTS SQ_PRODUCT_IDT START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SQ_SALES_IDT START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SQ_SALES_PRODUCT_IDT START WITH 1;